### ISSUE TITLE
Please limit this repo to Mapbox's open-licensed styles

### ISSUE THREAD

**Issue by michaelsteffen** [klokantech/osm2vectortiles-gl-styles#3]
Hi @klokan - Following up on my note over in https://github.com/osm2vectortiles/mapbox-gl-styles/issues/3#issuecomment-226269035, can you please remove the Mapbox Streets, Light, Dark, Emerald, and Satellite-Hybrid styles from this repo?  Thanks.

**Comment by klokan** [comment]
Done in e4c1b4ffee702ede94f024df7b84f3e811e45339

**Comment by michaelsteffen** [comment]
Thanks @klokan.
